---
env:
  contexts:
    - name: "Default Context"
      urls:
        - "FULL_URL"
      includePaths:
        - "^FULL_URL/.*"
      excludePaths:
        - "^https?://(?!HOSTPORT).*"
  parameters:
    failOnError: false
    failOnWarning: false
    progressToStdout: true

jobs:
  - type: passiveScan-config
    parameters: {}

  - type: activeScan-config
    parameters:
      threadPerHost: 5
      maxRuleDurationInMins: 5
      maxScanDurationInMins: 20
      handleAntiCSRFTokens: true
      injectPluginIdInHeader: true

  - type: activeScan
    parameters:
      context: "Default Context"
      threadPerHost: 5
      maxRuleDurationInMins: 5
      maxScanDurationInMins: 20
    policyDefinition:
      defaultStrength: Medium
      defaultThreshold: Low
      rules:
        - id: 40018
          strength: High
          threshold: Low
        - id: 90020
          strength: Medium
          threshold: Low
        - id: 40012
          strength: High
          threshold: Low
        - id: 40014
          strength: High
          threshold: Low

  - type: passiveScan-wait
    parameters: {}

  - type: report
    parameters:
      template: traditional-html
      reportDir: 'REPORT_DIR'
      reportFile: report
      reportTitle: "ZAP DAST Report Frontend"

  - type: report
    parameters:
      template: traditional-json
      reportDir: 'REPORT_DIR'
      reportFile: report
      reportTitle: "ZAP DAST Report Frontend"